name = "the-sect-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[[d1_databases]]
binding = "DB"
database_name = "the-sect-db"
database_id = "3acf9125-bb18-4887-bbc7-ac6c9ed941e8"

[[kv_namespaces]]
binding = "TOP10_CACHE"
id = "5c181d9fabcc4c1a83a4b6c00d3a7421"

[[kv_namespaces]]
binding = "CULT_COUNTERS"
id = "14a2c2e1dbb14b45ba5024cbc58fdda5"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "403d6e1ed5dd49738952aa562255b778"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "the-sect-assets"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDurableObject"
script_name = "the-sect-api"

[[migrations]]
tag = "v1"
new_classes = ["RoomDurableObject"]

[triggers]
crons = ["*/2 * * * *"]