name = "the-sect-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[[d1_databases]]
binding = "DB"
database_name = "the-sect-db"
database_id = "YOUR_DATABASE_ID"

[[kv_namespaces]]
binding = "TOP10_CACHE"
id = "YOUR_TOP10_CACHE_ID"

[[kv_namespaces]]
binding = "CULT_COUNTERS"
id = "YOUR_CULT_COUNTERS_ID"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "YOUR_RATE_LIMITS_ID"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "the-sect-assets"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDurableObject"
script_name = "the-sect-api"

[[migrations]]
tag = "v1"
new_classes = ["RoomDurableObject"]

[triggers]
crons = ["*/2 * * * *"]